# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValifyFaceScan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	 
   pod 'ValifyFaceScanML'
  # Pods for ValifyFaceScan

end
